// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8zEph_Qj2MPFsgPXr3RrWhHKXdmUk718',
    appId: '1:828867486553:web:a609fe6d63f4372f302248',
    messagingSenderId: '828867486553',
    projectId: 'grihsetu-a82d1',
    authDomain: 'grihsetu-a82d1.firebaseapp.com',
    storageBucket: 'grihsetu-a82d1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOXTA3uYKhVrod6ywvrX295uTbYcdz-yI',
    appId: '1:828867486553:android:ba51845f63e17364302248',
    messagingSenderId: '828867486553',
    projectId: 'grihsetu-a82d1',
    storageBucket: 'grihsetu-a82d1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3EeYc66e_h0qpmXAwsiNI2RgH-EFEalI',
    appId: '1:828867486553:ios:ccf0906634ae0ad2302248',
    messagingSenderId: '828867486553',
    projectId: 'grihsetu-a82d1',
    storageBucket: 'grihsetu-a82d1.firebasestorage.app',
    iosBundleId: 'com.example.grihsetu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3EeYc66e_h0qpmXAwsiNI2RgH-EFEalI',
    appId: '1:828867486553:ios:ccf0906634ae0ad2302248',
    messagingSenderId: '828867486553',
    projectId: 'grihsetu-a82d1',
    storageBucket: 'grihsetu-a82d1.firebasestorage.app',
    iosBundleId: 'com.example.grihsetu',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB8zEph_Qj2MPFsgPXr3RrWhHKXdmUk718',
    appId: '1:828867486553:web:44cc8313513bea29302248',
    messagingSenderId: '828867486553',
    projectId: 'grihsetu-a82d1',
    authDomain: 'grihsetu-a82d1.firebaseapp.com',
    storageBucket: 'grihsetu-a82d1.firebasestorage.app',
  );
}
